version: '3'
services:
  nginx:
    image: nginx:1.23.1
    container_name: nginx
    depends_on:
      - php
    links:
      - php
    volumes:
      - ./www:/var/www/
      - ./docker/nginx:/etc/nginx/conf.d/
    ports:
      - "80:80"

  php:
    image: php:8.1.10-fpm
    volumes:
      - ./www:/var/www/